version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_API_URL=${AUTH_API_URL}
      - FLASK_APP=run.py
    volumes:
      - ./:/app

