version: '3.8'
services:
  frontend_service:
    container_name: frontend_container
    image: frontend_image:v1.0.0
    restart: always
    build: .
    environment:
      - AUTH_API_URL=http://192.168.0.150:3000
    networks:
      - db_network
      - web_network
  nginx_service:
    container_name: nginx_container
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - frontend_service
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 