version: "3.0"
services:
  currencies:
    build:
      context: currencies/v3
    image: currencies:v3
    container_name: currencies
    ports:
      - '5000:5000'
    #volumes:
    #  - data:/app
    restart: always

  exchange:
    build:
      context: exchange
    image: echange:v1
    container_name: exchange
    ports:
      - '8080:8080'
    #volumes:
    #  - data:/app
    restart: always

  frontend:
    build:
      context: frontend/v3.1
    image: frontend:v1
    restart: always
    container_name: frondend
    ports:
      - 3000:3000

  frontend:
    build:
      context: history
    image: history:v1
    restart: always
    container_name: history
